services:

  mysql:
    image: mysql
    restart: unless-stopped
    networks:
      - internal
    ports:
      - "3306:3306"
    volumes:
      - ./local_data_save:/var/lib/mysql
      - ./dbScripts:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    deploy:
      resources:
        limits:
          memory: 1024M
    command: [ 'mysqld', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci' ]

  api:
    build:
      context: .
      dockerfile: ./Dockerfile
    networks:
      - internal
      - external
    ports:
      - "8089:8089"
    restart: unless-stopped

networks:
  external:
    driver: bridge
  internal:
    driver: bridge